### ISSUE TITLE
Why is everything deleted?

### ISSUE THREAD

**Issue by legodude17** [Coalpha/code.colegannon#20]

**Comment by Coalpha** [comment]
I'm making separate repositories for things that are on code.colegannon.com. I'm gonna start working on my portfolio and when I do, I'd like that to be one of the only things that's on my website. Dogrolld is cool and all but when it comes down to it, I don't want it on the same domain as some code that might be showcased in my portfolio

**Comment by legodude17** [comment]
You should put you portfolio on `colegannon.com`, instead of `code.colegannon.com`.
