### ISSUE TITLE
Can't scroll to bottom of html tester

### ISSUE THREAD

**Issue by j1ng3r** [Coalpha/code.colegannon#8]
Type in about 150 lines of code. The textarea continues far down below the page, with the content, but that part is not visible.

**Comment by Coalpha** [comment]
I think I know why that is. Check the CSS for `overflow:hidden`. That's probably your issue. Change that value for the textarea. I will remind you though. This HTML tester wasn't meant for editing things.

**Comment by legodude17** [comment]
We should make one that is.

**Comment by legodude17** [comment]
This should be closed, we have a new tester now. @Coalpha
